title:              Cube's Workshop
email:              lasurvivor1787@gmail.com
description:        Autonomy Engineer
author:             Robert Hu
baseurl:            "/homepage"
url:                "https://LAsurvivor.github.io"
theme: jekyll-theme-clean-blog

# Social Profiles
twitter_username:   LAsurvivor1787
github_username:    LAsurvivor
facebook_username:  ZhaohanHu
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-166297067-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
